version: '3'
services:
  bot:
    image: iwatkot/frb:latest
    container_name: frb
    restart: always
    pull: always
    depends_on:
      - webserver
    networks:
      - fn
    extra_hosts:
      - "host.docker.internal:host-gateway"
  webserver:
    image: iwatkot/frs:latest
    container_name: frs
    restart: always
    pull: always
    ports:
      - 80:80
    networks:
      - fn
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  fn:
